# Generated by Django 5.2.3 on 2025-07-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
