# Generated by Django 5.2.3 on 2025-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_course_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="course_preview/"),
        ),
    ]
